### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory on v0.22.0

### ISSUE THREAD

**Issue by jgonian** [arktekk/sbt-aether-deploy#56]
When publishing using version `0.22.0` I get the following error:
```
java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
[error] 	at org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:61)
[error] 	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:44)
[error] 	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:46)
[error] 	at org.apache.http.conn.ssl.SSLSocketFactory.<clinit>(SSLSocketFactory.java:153)
[error] 	at org.eclipse.aether.transport.http.GlobalState.newConnectionManager(GlobalState.java:175)
[error] 	at org.eclipse.aether.transport.http.LocalState.<init>(LocalState.java:63)
[error] 	at org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:137)
[error] 	at org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:102)
[error] 	at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:113)
[error] 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:125)
[error] 	at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:175)
[error] 	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:116)
[error] 	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:243)
[error] 	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:223)
[error] 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:384)
[error] 	at aether.AetherPlugin.deployIt(Plugin.scala:127)
[error] 	at aether.AetherPlugin.deployIt$(Plugin.scala:104)
[error] 	at aether.AetherPlugin$.deployIt(Plugin.scala:26)
[error] 	at aether.AetherPlugin.$anonfun$deployTask$2(Plugin.scala:74)
[error] 	at aether.AetherPlugin.$anonfun$deployTask$2$adapted(Plugin.scala:73)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at org.apache.http.conn.ssl.AbstractVerifier.<init>(AbstractVerifier.java:61)
[error] 	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<init>(AllowAllHostnameVerifier.java:44)
[error] 	at org.apache.http.conn.ssl.AllowAllHostnameVerifier.<clinit>(AllowAllHostnameVerifier.java:46)
[error] 	at org.apache.http.conn.ssl.SSLSocketFactory.<clinit>(SSLSocketFactory.java:153)
[error] 	at org.eclipse.aether.transport.http.GlobalState.newConnectionManager(GlobalState.java:175)
[error] 	at org.eclipse.aether.transport.http.LocalState.<init>(LocalState.java:63)
[error] 	at org.eclipse.aether.transport.http.HttpTransporter.<init>(HttpTransporter.java:137)
[error] 	at org.eclipse.aether.transport.http.HttpTransporterFactory.newInstance(HttpTransporterFactory.java:102)
[error] 	at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:113)
[error] 	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:125)
[error] 	at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:175)
[error] 	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:116)
[error] 	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:243)
[error] 	at org.eclipse.aether.internal.impl.DefaultDeployer.deploy(DefaultDeployer.java:223)
[error] 	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:384)
[error] 	at aether.AetherPlugin.deployIt(Plugin.scala:127)
[error] 	at aether.AetherPlugin.deployIt$(Plugin.scala:104)
[error] 	at aether.AetherPlugin$.deployIt(Plugin.scala:26)
[error] 	at aether.AetherPlugin.$anonfun$deployTask$2(Plugin.scala:74)
[error] 	at aether.AetherPlugin.$anonfun$deployTask$2$adapted(Plugin.scala:73)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (aetherDeploy) java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
```

The error only occurs when publishing to an `https` repository

The error seems to be a regression from https://github.com/arktekk/sbt-aether-deploy/commit/db80180553f3420ca0519bccc89d13b8c2c428ef#diff-fdc3abdfd754eeb24090dbd90aeec2ceL25. Adding the `commons-logging` dependency back should solve this issue.
